name: Feature build
on:
  push:
    branches-ignore:
      - master
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # install ubuntu deps
      - run: sudo apt-get install xvfb

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      # set up tests
      - run: yarn install

      # run tests
      - run: xvfb-run --auto-servernum yarn test:ci

      # build
      - run: yarn build:prod
